services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'    
      CLUSTER_HOSTNAME: 'node1'
      DEFAULT_VECTORIZER_MODULE: 'none'

  action_server:
    build:
      context: ..
      dockerfile: ./src/rasa_app/Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - ./rasa_app/actions:/app/actions
      - ./embed:/app/src/embed
      - ./chat:/app/src/chat
    env_file:
      - .env  # Tự động nạp GROQ_API_KEY, MODEL_NAME, vv. từ file .env
    environment:
      - WEAVIATE_HOST=weaviate # Tên service của Weaviate trong mạng Docker
    depends_on:
      - weaviate

  rasa_server:
    image: rasa/rasa:latest-full
    ports:
      - "5005:5005"
    volumes:
      - ./rasa_app:/app
    # CẬP NHẬT: Thêm chỉ định endpoints.yml để Rasa biết Action Server ở đâu
    command: run --enable-api --cors "*" --endpoints endpoints.yml
    depends_on:
      - action_server

volumes:
  weaviate_data: